// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkprO4oJRDmveZqYv51cbbqHiQwIj3WP4',
    appId: '1:835515540639:web:ed2d8d0d9589af564eaeaa',
    messagingSenderId: '835515540639',
    projectId: 'rental-system-9422a',
    authDomain: 'rental-system-9422a.firebaseapp.com',
    storageBucket: 'rental-system-9422a.appspot.com',
    measurementId: 'G-494286MW8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApVJuP4crU5KpHHi9Tl42P83bHBm8PoCU',
    appId: '1:835515540639:android:22d59a4460b8ffaf4eaeaa',
    messagingSenderId: '835515540639',
    projectId: 'rental-system-9422a',
    storageBucket: 'rental-system-9422a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlUUOxb2OIg0GCcX3qUGLYTCagT035gs4',
    appId: '1:835515540639:ios:a2081435f74965224eaeaa',
    messagingSenderId: '835515540639',
    projectId: 'rental-system-9422a',
    storageBucket: 'rental-system-9422a.appspot.com',
    iosClientId: '835515540639-et8d64bg6mi3jtq39kfq24skpvvabgcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalOwner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlUUOxb2OIg0GCcX3qUGLYTCagT035gs4',
    appId: '1:835515540639:ios:a67e4fc4063ade2d4eaeaa',
    messagingSenderId: '835515540639',
    projectId: 'rental-system-9422a',
    storageBucket: 'rental-system-9422a.appspot.com',
    iosClientId: '835515540639-90m7gm7vvt90m47krdc61i4pktreofc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalOwner.RunnerTests',
  );
}
